#ifdef DEFINE_TOKENKIND

DEFINE_TOKENKIND(Unknown, NULL)
DEFINE_TOKENKIND(Identifier, NULL)
DEFINE_TOKENKIND(Equals, "=")
DEFINE_TOKENKIND(Plus, "+")
DEFINE_TOKENKIND(Minus, "-")
DEFINE_TOKENKIND(Asterisk, "*")
DEFINE_TOKENKIND(Slash, "/")
DEFINE_TOKENKIND(Number, NULL)
DEFINE_TOKENKIND(LeftParen, "(")
DEFINE_TOKENKIND(RightParen, ")")
DEFINE_TOKENKIND(LeftBracket, "{")
DEFINE_TOKENKIND(RightBracket, "}")
DEFINE_TOKENKIND(Comma, ",")
DEFINE_TOKENKIND(EndOfInput, NULL) // must be last element

#endif
