#if defined(DEFINE_TOKENKIND_MANUAL) && \
    defined(DEFINE_TOKENKIND_COMPLEX) && \
    defined(DEFINE_TOKENKIND_SIMPLE)
DEFINE_TOKENKIND_MANUAL(Unknown)

DEFINE_TOKENKIND_COMPLEX(Identifier, matchIdentifier)
DEFINE_TOKENKIND_COMPLEX(Number, matchNumber) 
DEFINE_TOKENKIND_COMPLEX(Whitespace, matchWhitespace)  

DEFINE_TOKENKIND_SIMPLE(Equals, '=')
DEFINE_TOKENKIND_SIMPLE(Plus, '+')
DEFINE_TOKENKIND_SIMPLE(Minus, '-')
DEFINE_TOKENKIND_SIMPLE(Asterisk, '*')
DEFINE_TOKENKIND_SIMPLE(Slash, '/')
DEFINE_TOKENKIND_SIMPLE(LeftParen, '(')
DEFINE_TOKENKIND_SIMPLE(RightParen, ')')
DEFINE_TOKENKIND_SIMPLE(LeftBracket, '{')
DEFINE_TOKENKIND_SIMPLE(RightBracket, '}')
DEFINE_TOKENKIND_SIMPLE(Comma, ',')

DEFINE_TOKENKIND_MANUAL(EndOfInput) // must be last element
#else
#  ifdef DEFINE_TOKENKIND
#    define DEFINE_TOKENKIND_MANUAL(a)     DEFINE_TOKENKIND(a)
#    define DEFINE_TOKENKIND_COMPLEX(a,b)  DEFINE_TOKENKIND(a)
#    define DEFINE_TOKENKIND_SIMPLE(a,b)   DEFINE_TOKENKIND(a)
#    include "TokenKind.h"
#    undef DEFINE_TOKENKIND_SIMPLE
#    undef DEFINE_TOKENKIND_MANUAL
#    undef DEFINE_TOKENKIND_COMPLEX  
#  endif
#endif
